# Generated by Django 5.2.14 on 2026-05-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyServiceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_key', models.CharField(max_length=32, unique=True, verbose_name='מזהה שירות')),
                ('enabled', models.BooleanField(default=True, verbose_name='מופעל')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='הערה')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'מצב שירות Flask',
                'verbose_name_plural': 'מצבי שירותי Flask',
            },
        ),
    ]
